### ISSUE TITLE
SD image won't boot

### ISSUE THREAD

**Issue by QB4-dev** [joelguittet/meta-somlabs#1]
Tried to build image for  **sls16y2_792c_512r_sd_0sf** and boot process stops at:
`
waiting for root device /dev/mmcblk1p1....
`

I did some tests earlier in my work, and I'm faced the same issue with my device-tree. Most probably usdhc1 controller must be also configured to boot from mmc correctly - I am not sure yet. 

I think that I will fix it sooner or later because I've got visionsom6ull board with mmc slot to test this image. I'll left this issue opened until I find the fix

**Comment by myfreescalewebpage** [comment]
@QB4-dev thanks for testing, let me known of the progress on it, the issue remains open until it is solved.

EDIT : u-boot config in the machine can also be something to check.

**Comment by QB4-dev** [comment]
Solved here:
https://github.com/myfreescalewebpage/meta-somlabs/pull/2
